// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnrgirjdcxyeqjcgcjon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpucmdpcmpkY3h5ZXFqY2djam9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTA0NDIsImV4cCI6MjA3Mzc2NjQ0Mn0.k3RWnbOayyE-0LR7XXdra3PFzBcqtayXr-rc9ytHUaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});